POST http://greasy-rosella-urbanflowai-271435e5.koyeb.app/api/usuario/create
Content-Type: application/json

{
  "nome": "admin",
  "email": "leandrohenrique.denise.com",
  "password": "123",
  "telefone": "1194844754"
}

###

GET http://localhost:8000/api/usuario/email/leandrohenrique.denise@gmail.com

###

POST greasy-rosella-urbanflowai-271435e5.koyeb.app/api/auth/login/
Content-Type: application/json

{
  "email": "leandrohenrique.denise@gmail.com",
  "password": "123"
}

###

###

POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
  "nome": "admin",
  "email": "leandrohenrique.denise@gmail.com",
  "password": "123"
}

###
###

POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
  "nome": "admin",
  "email": "leandrohenrique.denise@gmail.com",
  "password": "123"
}

###


POST greasy-rosella-urbanflowai-271435e5.koyeb.app/api/2fa/teste/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTBhYWQxYi1mOGJjLTRhNjgtYjBmYy01OGNjNmQ2ODIwOTAiLCJlbWFpbCI6ImxlYW5kcm9oZW5yaXF1ZS5kZW5pc2VAZ21haWwuY29tIiwiaWF0IjoxNzY0NjEyNzA0LCJleHAiOjE3NjUyMTc1MDR9.0XTH4Hk2KP0_UcUS_7SLJp8bMx0H0SXCAWSF3HZW0V4



### 
###


POST http://localhost:8000/api/2fa/request/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTBhYWQxYi1mOGJjLTRhNjgtYjBmYy01OGNjNmQ2ODIwOTAiLCJlbWFpbCI6ImxlYW5kcm9oZW5yaXF1ZS5kZW5pc2VAZ21haWwuY29tIiwiaWF0IjoxNzY0OTY0NzMzLCJleHAiOjE3NjU1Njk1MzN9.T3tRxHvKvb6EmBhjb9Iqh8CFqf0Yx4F1Jf0RWrobo9A



### 

POST https://greasy-rosella-urbanflowai-271435e5.koyeb.app/api/2fa/request
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTBhYWQxYi1mOGJjLTRhNjgtYjBmYy01OGNjNmQ2ODIwOTAiLCJlbWFpbCI6ImxlYW5kcm9oZW5yaXF1ZS5kZW5pc2VAZ21haWwuY29tIiwiaWF0IjoxNzY0NzA3NzY2LCJleHAiOjE3NjUzMTI1NjZ9.uhS9_7KPT5W3x853TGDrPrzcD3eZXOKclYFYuHatkKA


###

POST greasy-rosella-urbanflowai-271435e5.koyeb.app/api/2fa/verify/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTBhYWQxYi1mOGJjLTRhNjgtYjBmYy01OGNjNmQ2ODIwOTAiLCJlbWFpbCI6ImxlYW5kcm9oZW5yaXF1ZS5kZW5pc2VAZ21haWwuY29tIiwiaWF0IjoxNzY0NjEyNzA0LCJleHAiOjE3NjUyMTc1MDR9.0XTH4Hk2KP0_UcUS_7SLJp8bMx0H0SXCAWSF3HZW0V4
Content-Type: application/json

{
  "code": "245104"
}
###

POST http://localhost:8000/api/2fa/verify/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTBhYWQxYi1mOGJjLTRhNjgtYjBmYy01OGNjNmQ2ODIwOTAiLCJlbWFpbCI6ImxlYW5kcm9oZW5yaXF1ZS5kZW5pc2VAZ21haWwuY29tIiwiaWF0IjoxNzY0NjEyNzA0LCJleHAiOjE3NjUyMTc1MDR9.0XTH4Hk2KP0_UcUS_7SLJp8bMx0H0SXCAWSF3HZW0V4
Content-Type: application/json

{
  "code": "875899"
}
